<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="FunctionalTestingZeroBank" duration-ms="4027" started-at="2020-12-18T22:09:34Z" finished-at="2020-12-18T22:09:38Z">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="1496" started-at="2020-12-18T22:09:34Z" finished-at="2020-12-18T22:09:36Z">
      <class name="testcases.TC001_LoginVerify">
        <test-method status="FAIL" signature="verifyLogin()[pri:0, instance:testcases.TC001_LoginVerify@78b1cc93]" name="verifyLogin" duration-ms="886" started-at="2020-12-18T17:09:34Z" finished-at="2020-12-18T17:09:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Zero - Account Summary] but found [Zero - Log in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Zero - Account Summary] but found [Zero - Log in]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at testcases.TC001_LoginVerify.verifyLogin(TC001_LoginVerify.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
      </class> <!-- testcases.TC001_LoginVerify -->
    </test> <!-- Login Test -->
    <test name="AddPayee Test" duration-ms="1540" started-at="2020-12-18T22:09:36Z" finished-at="2020-12-18T22:09:37Z">
      <class name="testcases.TC003_AddpayeeVerify">
        <test-method status="PASS" signature="verifyAddpayee()[pri:0, instance:testcases.TC003_AddpayeeVerify@3745e5c6]" name="verifyAddpayee" duration-ms="1517" started-at="2020-12-18T17:09:36Z" finished-at="2020-12-18T17:09:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddpayee -->
      </class> <!-- testcases.TC003_AddpayeeVerify -->
    </test> <!-- AddPayee Test -->
    <test name="Funds Transfer Test" duration-ms="980" started-at="2020-12-18T22:09:37Z" finished-at="2020-12-18T22:09:38Z">
      <class name="testcases.TC002_FundstransferVerify">
        <test-method status="PASS" signature="init()[pri:0, instance:testcases.TC002_FundstransferVerify@d83da2e]" name="init" is-config="true" duration-ms="6340" started-at="2020-12-18T17:09:28Z" finished-at="2020-12-18T17:09:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="verifyfundstransfer()[pri:0, instance:testcases.TC002_FundstransferVerify@d83da2e]" name="verifyfundstransfer" duration-ms="962" started-at="2020-12-18T17:09:37Z" finished-at="2020-12-18T17:09:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyfundstransfer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TC002_FundstransferVerify@d83da2e]" name="tearDown" is-config="true" duration-ms="773" started-at="2020-12-18T17:09:38Z" finished-at="2020-12-18T17:09:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TC002_FundstransferVerify -->
    </test> <!-- Funds Transfer Test -->
  </suite> <!-- FunctionalTestingZeroBank -->
</testng-results>
